# Generated by Django 4.0.4 on 2022-05-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0002_mod_type_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='comp_estado',
            field=models.CharField(choices=[('disponivel/com caixa', 'DC'), ('disponivel/sem caixa', 'DS'), ('indisponivel', 'IND'), ('cedido', 'C')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comp',
            name='comp_status',
            field=models.CharField(choices=[('operante', 'O'), ('inoperante', 'I')], max_length=15),
        ),
    ]
